Improve clean script

diff --git a/clean b/clean
--- a/clean
+++ b/clean
@@ -1,24 +1,42 @@
 #!/usr/bin/env bash
 set -u
 
-DID_SOMETHING=0
-
-deleteIfExists() {
-    if [[ -f "$2" || -d "$2" ]]; then
-        printf "Removing $1 ... "
-        rm -rf $2
-        greentext "done"
-        DID_SOMETHING=1
-    fi
-}
-
 greentext() {
     printf "\x1B[32m%b\e[0m\n" "$1"
 }
 
+successOrFail() {
+    if [[ $1 == 0 ]]; then
+        greentext $2
+    else
+        redtext $3
+        echo $4
+        exit 1
+    fi
+}
+
+deleteIfExists() {
+    if [[ -f "$2" || -d "$2" ]]; then
+        printf "Removing $1 ... "
+            rm -rf $2
+        successOrFail $? 'done' 'error' 'Could not remove file.'
+        DID_SOMETHING=1
+    fi
+}
+
+DID_SOMETHING=0
+for var in "$@"
+do
+    if [[ $var == "all" ]]; then
+        echo "Psst.. Btw, no need to type 'all' anymore. The ./clean script is magically smart =)"
+    fi
+done
+
 if [[ -f "./.lock" ]]; then
 	source .lock
+    printf "docker-compose down\t... "
 	eval "docker-compose $DOCKER_ARGS down"
+    successOrFail $? 'done' 'error' 'Could not docker-compose down.'
 	DID_SOMETHING=1
 fi
 
