Add mainnet and testnet configurations

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-set -u
+# set -u
 
 abort() {
     printf "%s" "$@"
@@ -60,6 +60,9 @@ fi
 BTK_GENERATE_ADDRESS=bchreg:qzerfrqkvsclmrlx3hzl0j2ac2eh0k88wqa0efygtm
 BTK_WIF=cUDjy47QLpAUyv1beivDPoYCHjCRVqwRMwCuSnkdF4teVFBDD1ip
 
+BTK_REGTEST=0
+BTK_TESTNET=0
+BTK_MAINNET=0
 BTK_SLEEP_TIME=${sleep:-6}
 BTK_BLOCKS=${blocks:-200}
 BTK_ENV=$(uname)
@@ -70,6 +73,8 @@ BTK_BCHAPI=0 # Default incl NGINX
 BTK_SLP=0 # Default incl SLPDB, slpserve
 
 BTK_DOCKER_NETWORK=${BTK_DOCKER_NETWORK:-"bch-toolkit-network"}
+ENV_FILE=./configs/env.env
+EXPOSE_PORTS=0
 
 # Process user arguments, or display usage message
 if [[ ! -z "${1:-}" ]]; then
@@ -78,6 +83,10 @@ if [[ ! -z "${1:-}" ]]; then
         if [[ $var == "bcnh" ]]; then
             abort "No command 'bcnh'. Did you mean 'bchn' ?"
         fi
+        [[ $var == "regtest" ]] && BTK_REGTEST=1
+        [[ $var == "testnet" ]] && BTK_TESTNET=1
+        [[ $var == "mainnet" ]] && BTK_MAINNET=1
+        [[ $var == "expose-ports" ]] && EXPOSE_PORTS=1
 		[[ $var == "bu" ]] && BTK_UNLIMITED=1
         [[ $var == "bchn" ]] && BTK_CASHNODE=1
 		[[ $var == "bchrest" ]] && BTK_BCHREST=1
@@ -119,6 +128,25 @@ else
 fi
 
 ### Catch exceptions
+#Only one network may be selected
+if [[ $BTK_REGTEST == 1 && $BTK_TESTNET == 1 ]]; then
+    echo "Only one network may be selected at a time."
+    echo "Please select only one."
+    abort
+fi
+
+if [[ $BTK_REGTEST == 1 && $BTK_MAINNET == 1 ]]; then
+    echo "Only one network may be selected at a time."
+    echo "Please select only one."
+    abort
+fi
+
+if [[ $BTK_MAINNET == 1 && $BTK_TESTNET == 1 ]]; then
+    echo "Only one network may be selected at a time."
+    echo "Please select only one."
+    abort
+fi
+
 # User cannot have more than one node
 if [[ $BTK_UNLIMITED == 1 && $BTK_CASHNODE == 1 ]]; then
     echo "bch-toolkit cannot run both Bitcoin Unlimited and BitcoinCashNode at the same time."
@@ -132,6 +160,7 @@ if [[ $BTK_UNLIMITED == 0 && $BTK_CASHNODE == 0 ]]; then
     abort
 fi
 ### End exception catching
+
 
 # Check that Python3 is installed
 lookingfor "Python 3"
@@ -191,6 +220,130 @@ if [[ $BTK_BCHAPI == 1 ]]; then
 	fi
 fi
 
+source ./configs/pass.conf
+
+if [[ $BTK_UNLIMITED == 1 ]]; then
+    cp ./configs/default_bu.conf ./configs/bitcoin-unlimited.conf
+    NODE_CONFIG_FILE=./configs/bitcoin-unlimited.conf
+else
+    cp ./configs/default_bitcoincashnode.conf ./configs/bitcoincashnode.conf
+    NODE_CONFIG_FILE=./configs/bitcoincashnode.conf
+fi
+
+if [[ $BTK_SLP == 1 ]]; then
+    if [[ -z ${MONGO_USER} ]]; then
+        printf "SLPDB uses mongodb, a username and password is recommended."
+        printf "\n Please enter a username for mongodb:\n"
+        read MONGO_USER
+        echo "export MONGO_USER=$MONGO_USER">>./configs/pass.conf
+    fi
+    if [[ -z ${MONGO_PASS}  ]]; then
+        printf "\n Please enter a password for mongodb:"
+        read MONGO_PASS
+        echo "export MONGO_PASS=$MONGO_PASS">>./configs/pass.conf
+    fi
+fi
+
+
+if [[ $BTK_MAINNET == 1 ]]; then
+    # Check if password already set
+    if [[ -z ${RPC_PASSWORD} ]]; then
+        printf "\n Please enter a username for the node RPC connection:\n"
+        read NEW_RPC_USERNAME
+        printf "\n Please enter a password for the RPC connection on the node.\n This will be stored in the pass.conf file in the configs directory.\n"
+        read NEW_RPC_PASSWORD
+        printf $NEW_RPC_PASSWORD
+        
+        echo "rpcuser=$NEW_RPC_USERNAME">>$NODE_CONFIG_FILE
+        echo "rpcpassword=$NEW_RPC_PASSWORD">>$NODE_CONFIG_FILE
+
+        # Add to pass.conf
+        echo "export RPC_USERNAME=$NEW_RPC_USERNAME">>./configs/pass.conf
+        echo "export RPC_PASSWORD=$NEW_RPC_PASSWORD">>./configs/pass.conf
+    else
+        printf "Password found\n"
+        echo "rpcuser=$RPC_USERNAME">>$NODE_CONFIG_FILE
+        echo "rpcpassword=$RPC_PASSWORD">>$NODE_CONFIG_FILE    
+    fi
+    
+    echo "rpcport=8332">>$NODE_CONFIG_FILE
+    echo "rpcbind=0.0.0.0:8332">>$NODE_CONFIG_FILE
+    echo "maxconnections=10">>$NODE_CONFIG_FILE
+
+    # Config env file for ./services
+    echo "export RPC_PORTS=8332">>$ENV_FILE
+    echo "export NETWORK=mainnet">>$ENV_FILE
+fi
+
+if [[ $BTK_TESTNET == 1 ]]; then
+    if [[ -z ${RPC_PASSWORD} ]];then
+        printf "\n Please enter a username for the node RPC connection:\n"
+        read NEW_RPC_USERNAME
+        printf "\n Please enter a password for the RPC connection on the node.\n This will be stored in the pass.conf file in the configs directory.\n"
+        read NEW_RPC_PASSWORD
+        printf $NEW_RPC_PASSWORD
+    
+        echo "rpcuser=$NEW_RPC_USERNAME">>$NODE_CONFIG_FILE
+        echo "rpcpassword=$NEW_RPC_PASSWORD">>$NODE_CONFIG_FILE
+
+        # Add to pass.conf
+        echo "export RPC_USERNAME=$NEW_RPC_USERNAME">>./configs/pass.conf
+        echo "export RPC_PASSWORD=$NEW_RPC_PASSWORD">>./configs/pass.conf
+    else
+        printf "Password found\n"
+        echo "rpcuser=$RPC_USERNAME">>$NODE_CONFIG_FILE
+        echo "rpcpassword=$RPC_PASSWORD">>$NODE_CONFIG_FILE    
+    fi
+
+    echo "testnet=1">>$NODE_CONFIG_FILE
+    echo "maxconnections=10">>$NODE_CONFIG_FILE
+    echo "rpcport=18332">>$NODE_CONFIG_FILE
+    echo "rpcbind=0.0.0.0:18332">>$NODE_CONFIG_FILE
+
+    # Config env file for ./services
+    echo "export RPC_PORTS=18332">>$ENV_FILE
+    echo "export NETWORK=testnet">>$ENV_FILE
+fi
+
+if [[ $BTK_REGTEST == 1 ]]; then
+    if [[ $BTK_UNLIMITED == 1 ]]; then
+        echo "regtest=1">>$NODE_CONFIG_FILE
+    else
+        echo "[regtest]">>$NODE_CONFIG_FILE
+    fi
+
+    if [[ -z "${RPC_PASSWORD}" ]]; then
+        printf "\n Please enter a username for the node RPC connection:\n"
+        read NEW_RPC_USERNAME
+        printf "\n Please enter a password for the RPC connection on the node.\n This will be stored in the pass.conf file in the configs directory.\n"
+        read NEW_RPC_PASSWORD
+    
+        echo "rpcuser=$NEW_RPC_USERNAME">>$NODE_CONFIG_FILE
+        echo "rpcpassword=$NEW_RPC_PASSWORD">>$NODE_CONFIG_FILE
+
+        # Add to pass.conf
+        echo "export RPC_USERNAME=$NEW_RPC_USERNAME">>./configs/pass.conf
+        echo "export RPC_PASSWORD=$NEW_RPC_PASSWORD">>./configs/pass.conf
+    else
+        echo "rpcuser=$RPC_USERNAME">>$NODE_CONFIG_FILE
+        echo "rpcpassword=$RPC_PASSWORD">>$NODE_CONFIG_FILE    
+    fi
+    echo "rpcport=18443">>$NODE_CONFIG_FILE
+    echo "rpcbind=0.0.0.0:18443">>$NODE_CONFIG_FILE
+    echo "maxconnections=0">>$NODE_CONFIG_FILE
+
+    # Config env file for ./services
+    echo "export RPC_PORTS=18443">>$ENV_FILE
+    echo "export NETWORK=regtest">>$ENV_FILE
+
+fi
+
+# Here we need to copy the conf and append based on network and values before
+# echo "RPC_PASSWORD=$NEW_RPC_PASSWORD">>./configs/pass.conf
+
+source ./configs/pass.conf
+source ./configs/env.env
+
 # Set up the config file based on user input
 printf "Creating config files ... "
 python3 - << EOF
@@ -206,24 +359,44 @@ config = {
 }
 
 if ${BTK_UNLIMITED}:
-    config["node"] = "bitcoinunlimited"
+    if ${EXPOSE_PORTS}:
+        config["node"] = "bitcoinunlimited_ports"
+    else:
+        config["node"] = "bitcoinunlimited"
 
 if ${BTK_CASHNODE}:
-    config["node"] = "bitcoincashnode"
-    config["indexer"] = "fulcrum"
+    if ${EXPOSE_PORTS}:
+        config["node"] = "bitcoincashnode_ports"
+        config["indexer"] = "fulcrum_ports"
+    else:
+        config["node"] = "bitcoincashnode"
+        config["indexer"] = "fulcrum"
 
 if ${BTK_BCHREST}:
-    config["rest"] += ["opensight"]
-    config["rest"] += ["bchrest"]
+    if ${EXPOSE_PORTS}:
+        config["rest"] += ["opensight_ports"]
+        config["rest"] += ["bchrest_ports"]
+    else:
+        config["rest"] += ["opensight"]
+        config["rest"] += ["bchrest"]
 
 if ${BTK_BCHAPI}:
-    config["rest"] += ["nginx"]
-    config["rest"] += ["bchapi"]
+    if ${EXPOSE_PORTS}:
+        config["rest"] += ["nginx_ports"]
+        config["rest"] += ["bchapi_ports"]
+    else:
+        config["rest"] += ["nginx"]
+        config["rest"] += ["bchapi"]
 
 if ${BTK_SLP}:
-    config["slp"] += ["mongodb"]
-    config["slp"] += ["slpdb"]
-    config["slp"] += ["slpserve"]
+    if ${EXPOSE_PORTS}:
+        config["slp"] += ["mongodb_ports"]
+        config["slp"] += ["slpdb"]
+        config["slp"] += ["slpserve_ports"]
+    else:
+        config["slp"] += ["mongodb"]
+        config["slp"] += ["slpdb"]
+        config["slp"] += ["slpserve"]
 
 config["network"] = "network"
 
@@ -261,10 +434,13 @@ eval "docker-compose -p bch-toolkit $DOCKER_ARGS pull"
 eval "docker-compose $DOCKER_ARGS up -d bch-node"
 sleep $BTK_SLEEP_TIME
 
-# Generate N blocks
-printf "Generating $BTK_BLOCKS initial blocks for regtest\t... "
-    eval "docker-compose $DOCKER_ARGS exec -T bch-node bitcoin-cli -conf=/bitcoin.conf generate $BTK_BLOCKS > /dev/null"
-successOrFail $? 'done' 'error' 'Could not create blocks.'
+
+if [[ $BTK_REGTEST == 1 ]]; then
+    # Generate N blocks
+    printf "Generating $BTK_BLOCKS initial blocks for regtest\t... "
+        eval "docker-compose $DOCKER_ARGS exec -T bch-node bitcoin-cli -conf=/bitcoin.conf generate $BTK_BLOCKS > /dev/null"
+    successOrFail $? 'done' 'error' 'Could not create blocks.'
+fi
 
 printf "Stopping local node\t... "
     sleep $BTK_SLEEP_TIME
