Reorganize entire bch-toolkit layout

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,51 +1,77 @@
 #!/usr/bin/env bash
 set -e
 
-echo "Setting up Bitcoin Unlimited node."
-echo "Checking that necessary software is available: "
+# Ensure working directory is clean before setup
+if [[ -f ".env" ]]; then
+	echo "It appears you've already run this setup script before."
+	echo "Please run the ./clean script before trying to setup again."
+	exit 1
+fi
 
+BTK_SLEEP_TIME=6
+BTK_BLOCKS=100
+BTK_GENERATE_ADDRESS=bchreg:qzerfrqkvsclmrlx3hzl0j2ac2eh0k88wqa0efygtm
+BTK_WIF=cUDjy47QLpAUyv1beivDPoYCHjCRVqwRMwCuSnkdF4teVFBDD1ip
 BTK_ENV=$(uname)
-BTK_JS_API=0
-BTK_SLPDB=0
 BTK_NODE=0
+BTK_REST=0
+BTK_SLPDB=0
+BTK_JS_API=0
+BTK_NGINX=0
+
 BTK_WALLET=0 # Under construction 
 
-BTK_REST=1 # must install until it's seperated from the docker-compose file
-# TODO: Edit the docker-compose file in such a way that REST isn't necessarily required 
+BTK_NETWORK="bitcoin-bridging"
 
 # Process user arguments, or display usage message
 if [[ ! -z $1 ]]; then
     for var in "$@"
     do
-		[[ $var == "js" ]] && BTK_JS_API=1
-		[[ $var == "slpdb" ]] && BTK_SLPDB=1
 		[[ $var == "node" ]] && BTK_NODE=1
-		[[ $var == "wallet" ]] && BTK_WALLET=1
 		[[ $var == "rest" ]] && BTK_REST=1
-
-		if [[ $var == "all" ]]; then
-			BTK_JS_API=1
-			BTK_SLPDB=1
-			BTK_NODE=1
+		[[ $var == "slpdb" ]] && BTK_SLPDB=1
+		if [[ $var == "wallet" ]]; then
 			BTK_WALLET=1
+			# BTK_NGINX=1
+		fi
+		if [[ $var == "js" ]]; then
+			BTK_JS_API=1
+			# BTK_NGINX=1
+		fi
+		if [[ $var == "default" ]]; then
+			BTK_NODE=1
 			BTK_REST=1
+			BTK_SLPDB=1
+		fi
+		if [[ $var == "all" ]]; then
+			BTK_NODE=1
+			BTK_REST=1
+			BTK_SLPDB=1
+			BTK_JS_API=1
+			BTK_WALLET=1
 		fi
     done
 else
     echo "usage: setup [command]"
-    echo "- node: BitcoinUnlimited node with electrs server"
-    echo "- rest: rest.bitcoin.com API service"
-    echo "- wallet: Electron Cash SLP wallet GUI application"
+    echo "- node: Bitcoin Cash Node with ElectrumX indexing server"
+    echo "- rest: rest.bitcoin.com API service with OpenSight"
+	echo "- slpdb: SLPDB token indexing server"
     echo "- js: JavaScript stack ready for BCH JS development"
+	echo "- wallet: Electron Cash SLP wallet GUI application"
     echo "- all: all of the above"
     exit 0 
 fi
 
-# Check that Docker, docker-compose, openssl, git, python3, and virtualenv are installed
+echo "Setting up bch-toolkit..."
+echo "Checking that necessary software is available: "
+
+# Check that Docker and docker-compose are installed
 echo "Looking for Docker..."
-if [ -x "$(command -v docker)" ]; then
-	# Note: The following line may seem useless, however it causes the scirpt to error
-	# if A) Docker is not currently running, or B) permissions are not set correctly
+if [[ -x "$(command -v docker)" ]]; then
+	# Note: The following line may seem useless, 
+	# however it causes the scirpt to error
+	# if A) Docker is not currently running, or 
+	# B) permissions are not set correctly
 	# on Linux or FreeBSD host
 	BTK_DOCKER_STATUS=`docker ps`
 	echo "Docker found."	
@@ -55,73 +81,128 @@ else
 fi
 
 echo "Looking for docker-compose..."
-if [ -x "$(command -v docker-compose)" ]; then
+if [[ -x "$(command -v docker-compose)" ]]; then
 	echo "Docker-compose found."
 else
 	echo "Docker-compose not found. Please install docker-compose."
 	exit 1 
 fi
 
-echo "Looking for openssl..."
-if [ -x "$(command -v openssl)" ]; then
-	echo "Openssl found."
-else
-	echo "Openssl not found. Please install openssl."
-	exit 1
+# Check and (if needed) create docker network for bch-toolkit
+if [[ -z $(docker network ls --filter name=^${BTK_NETWORK}$ --format="{{ .Name }}") ]]; then
+	docker network create ${BTK_NETWORK}
 fi
 
-echo "Looking for git..."
-if [ -x "$(command -v git)" ]; then
-	echo "Git found."
-else
-	echo "Git not found. Please install git."
-	exit 1
-fi
-
-# Check if network exists and create if it doesn't
-NETWORK_NAME=bitcoin-bridging
-if [ -z $(docker network ls --filter name=^${NETWORK_NAME}$ --format="{{ .Name }}") ] ; then 
-     docker network create ${NETWORK_NAME} ; 
-fi
-
-# Create new SSL certificate/key pair to be used on nginx server
-if [ -d "./cert" ]; then 
-	if [[ -f "./cert/cert.key" && -f "./cert/cert.crt" ]]; then
-	    echo "OpenSSL certificates already exist."
-	else
-	    echo "Removing previous certs directory"
-	    rm -rf ./cert
-	fi
-fi
-
-if [ ! -d "./cert" ]; then
-	mkdir ./cert
-	echo "Creating SSL certificate to use for nginx reverse proxy server."
-	openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
-		-keyout ./cert/cert.key \
-		-out ./cert/cert.crt \
-		-subj "/C=no/ST=no/L=no/O=no/OU=no/CN=no/emailAddress=no"
-fi
-
-
+# Configure docker-compose files for the selected stack
 if [[ $BTK_NODE == 1 ]]; then
+    # export COMPOSE_FILE="./dc_files/docker-compose.bitcoinunlimited.yml"
+    export COMPOSE_FILE="./dc_files/docker-compose.bitcoincashnode.yml"
+	
+    # export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.electrumx.yml"
+    
+	# The next steps initiate the regtest node before proceeding to the
+	# final configurations (which includes REST, OpenSight, Wallet, etc)
+
+	# Save state of compose_file (before initilizing node)
+	export PRE_NETWORK_FILE="$COMPOSE_FILE"
+
+	# Temporarily add network to docker-compose file
+	export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.network.yml"
+
+	# Create temporary env file
+	echo "COMPOSE_FILE=$COMPOSE_FILE" >> ".env"
+
+	# Initailze regtest node
 	echo "Starting local node servers..."
 	docker-compose up -d
-	sleep 5
+	sleep $BTK_SLEEP_TIME
 
-	# Generate some blocks
-	docker-compose exec -T bitcoind-regtest bitcoin-cli generate 210
+	# Generate N blocks
+    echo "Generating $BTK_BLOCKS blocks for regtest to address"
+    echo $BTK_GENERATE_ADDRESS
 
+    docker-compose exec -T bitcoind-regtest bitcoin-cli generatetoaddress $BTK_BLOCKS $BTK_GENERATE_ADDRESS > /dev/null
+    sleep $BTK_SLEEP_TIME
+    #docker-compose exec -T bitcoind-regtest bitcoin-cli generate $BTK_BLOCKS > /dev/null
+    
 	# Stop the server(s)
 	docker-compose stop 
 
-	#
-	touch .BTK-container-lock
+	# Remove temporary env file
+	rm ".env"
+
+	# Reset the compose_file
+	export COMPOSE_FILE="$PRE_NETWORK_FILE"
+    export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.fulcrum.yml"
+
 fi
 
+if [[ $BTK_NGINX == 1 ]]; then
+
+	# Check that openssl is installed and available
+	echo "Looking for openssl..."
+	if [[ -x "$(command -v openssl)" ]]; then
+		echo "Openssl found."
+	else
+		echo "Openssl not found. Please install openssl."
+		exit 1
+	fi
+
+	# Create new SSL certificate/key pair to be used on nginx server
+	if [[ -d "./configs/cert" ]]; then 
+		if [[ -f "./configs/cert/cert.key" && -f "./configs/cert/cert.crt" ]]; then
+			echo "OpenSSL certificates already exist."
+		else
+			echo "Removing previous certs directory"
+			rm -rf ./configs/cert
+		fi
+	fi
+
+	if [[ ! -d "./configs/cert" ]]; then
+		mkdir ./configs/cert
+		echo "Creating SSL certificate to use for nginx reverse proxy server."
+		openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
+			-keyout ./configs/cert/cert.key \
+			-out ./configs/cert/cert.crt \
+			-subj "/C=no/ST=no/L=no/O=no/OU=no/CN=no/emailAddress=no"
+	fi
+
+	export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.nginx.yml"
+
+fi
+
+if [[ $BTK_REST == 1 ]]; then
+	export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.opensight.yml"
+	export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.restapi.yml"
+fi
+
+if [[ $BTK_JS_API == 1 ]]; then
+	export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.bch-api.yml"
+fi
+
+if [[ $BTK_SLPDB == 1 ]]; then
+	export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.mongodb.yml"
+	export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.slpdb.yml"
+	export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.slpserve.yml"
+fi
+
+# Add network to docker-compose file
+export COMPOSE_FILE="$COMPOSE_FILE:./dc_files/docker-compose.network.yml"
+
+echo "COMPOSE_FILE=$COMPOSE_FILE" >> ".env"
 
 if [[ $BTK_WALLET == 1 ]]; then
 
+	# Check that git is installed
+	echo "Looking for git..."
+	if [[ -x "$(command -v git)" ]]; then
+		echo "Git found."
+	else
+		echo "Git not found. Please install git."
+		exit 1
+	fi
+
+	# Check that python3 is installed
 	if [ -x "$(command -v python3)" ]; then
 		echo "Python3 found."
 	else 
@@ -129,7 +210,7 @@ if [[ $BTK_WALLET == 1 ]]; then
 		exit 1
 	fi
 
-	# This is ugly for now but should work, will clean up in next commit
+	# This is ugly for now but should work, will clean up in future commit
 
 	echo "Looking for virtualenv..."
 	##
@@ -218,7 +299,7 @@ if [[ $BTK_WALLET == 1 ]]; then
 
 
     # Start the servers and get the genesis & verification block, and merkle root
-    if [ ! -f "./.BTK-container-lock" ]; then
+    if [ -f "./.env" ]; then
 
 		echo "Starting local node servers..."
 		docker-compose up -d
@@ -297,27 +378,4 @@ if [[ $BTK_WALLET == 1 ]]; then
 
 fi
 
-if [[ $BTK_JS_API == 1 ]]; then
-
-    git submodule update --init -- bch-api
-    cd bch-api && 
-    docker-compose build --no-cache &&
-    cd ..
-
-fi
-
-
-
-if [[ $BTK_SLPDB == 1 ]]; then
-
-    git submodule update --init -- slpdb
-    cd slpdb && 
-    docker-compose build --no-cache &&
-    cd ..
-fi
-
-
-
-
 echo "Done."
-
